hw/ssi/nuvoton: Change flash_size to uint64_t
Previously this was declared as a size_t field that's used as a
DEFINE_PROP_SIZE property. The implementation of DEFINE_PROP_SIZE uses a
uint64_t and emits a compilation error based on the type mismatch:

    $ make
    changing dir to build for /Library/Developer/CommandLineTools/usr/bin/make ""...
      GIT     ui/keycodemapdb meson tests/fp/berkeley-testfloat-3 tests/fp/berkeley-softfloat-3 dtc slirp
    [1/18] Generating qemu-version.h with a custom command (wrapped by meson to capture output)
    [2/18] Compiling C object libcommon.fa.p/hw_ssi_npcm7xx_fiu.c.o
    FAILED: libcommon.fa.p/hw_ssi_npcm7xx_fiu.c.o
    cc -m64 -mcx16 -Ilibcommon.fa.p -I../dtc/libfdt -I../slirp -I../slirp/src -I/usr/local/Cellar/pixman/0.40.0/include/pixman-1 -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include -I/usr/local/Cellar/jpeg/9e/include -I/opt/homebrew/Cellar/zstd/1.4.3//include -I/usr/local/Cellar/libusb/1.0.26/include/libusb-1.0 -I/usr/local/Cellar/glib/2.72.2/include -I/usr/local/Cellar/glib/2.72.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.72.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.45/include -fcolor-diagnostics -Wall -Winvalid-pch -std=gnu11 -O2 -g -iquote . -iquote /Users/pdel/qemu -iquote /Users/pdel/qemu/include -iquote /Users/pdel/qemu/tcg/i386 -DOS_OBJECT_USE_OBJC=0 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wstrict-prototypes -Wredundant-decls -Wundef -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing -fno-common -fwrapv -Wold-style-definition -Wtype-limits -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wempty-body -Wnested-externs -Wendif-labels -Wexpansion-to-defined -Wno-initializer-overrides -Wno-missing-include-dirs -Wno-shift-negative-value -Wno-string-plus-int -Wno-typedef-redefinition -Wno-tautological-type-limit-compare -Wno-psabi -fstack-protector-strong -DSTRUCT_IOVEC_DEFINED -MD -MQ libcommon.fa.p/hw_ssi_npcm7xx_fiu.c.o -MF libcommon.fa.p/hw_ssi_npcm7xx_fiu.c.o.d -o libcommon.fa.p/hw_ssi_npcm7xx_fiu.c.o -c ../hw/ssi/npcm7xx_fiu.c
    ../hw/ssi/npcm7xx_fiu.c:543:5: error: 'uint64_t *' (aka 'unsigned long long *') and 'typeof (((NPCM7xxFIUState *)0)->flash_size) *' (aka 'unsigned long *') are not pointers to compatible types
        DEFINE_PROP_SIZE("flash-size", NPCM7xxFIUState, flash_size, 0),
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/pdel/qemu/include/hw/qdev-properties.h:171:5: note: expanded from macro 'DEFINE_PROP_SIZE'
        DEFINE_PROP_UNSIGNED(_n, _s, _f, _d, qdev_prop_size, uint64_t)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/pdel/qemu/include/hw/qdev-properties.h:90:5: note: expanded from macro 'DEFINE_PROP_UNSIGNED'
        DEFINE_PROP(_name, _state, _field, _prop, _type,                       \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/pdel/qemu/include/hw/qdev-properties.h:71:15: note: expanded from macro 'DEFINE_PROP'
                + type_check(_type, typeof_field(_state, _field)),   \
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/pdel/qemu/include/qemu/compiler.h:67:35: note: expanded from macro 'type_check'
                               ~~~~~~ ^ ~~~~~~
    1 error generated.

Fixes: 73341fd328e36 ("hw/ssi: Make flash size a property in NPCM7XX FIU")
Signed-off-by: Peter Delevoryas <peter@pjd.dev>